export const INIT_GAME = 'INIT_GAME';
export const SET_GRID_CELL_TO_COMPARE = 'SET_GRID_CELL';
export const CLEAR_GRID_CELL_TO_COMPARE = 'CLEAR_GRID_CELL_TO_COMPARE';
export const SET_GRID_EMPTY_CELLS = 'SET_GRID_EMPTY_CELLS';
export const SET_GAME_GRID_DIMENSION = 'SET_GAME_GRID_DIMENSION';